.PHONY: clean All

All:
	@echo "----------Building project:[ Another - Debug ]----------"
	@cd "Another" && "$(MAKE)" -f  "Another.mk"
clean:
	@echo "----------Cleaning project:[ Another - Debug ]----------"
	@cd "Another" && "$(MAKE)" -f  "Another.mk" clean
